/**
 * Shared domain types for Jio.
 *
 * These types are storage-agnostic on purpose: they describe the domain, not a
 * particular database. Any new `Repo` implementation (Postgres, Firebase,
 * SQLite, an HTTP backend) only has to produce and accept these shapes.
 */

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

export type Cuisine =
  | "chinese"
  | "malay"
  | "indian"
  | "japanese"
  | "korean"
  | "thai"
  | "vietnamese"
  | "western"
  | "italian"
  | "local"
  | "halal"
  | "vegetarian"
  | "cafe"
  | "fast_food"
  | "food_court"
  | "dessert"
  | "modern"
  | "traditional";

/** 1 = under $8, 2 = $8-15, 3 = $15-30, 4 = over $30. */
export type BudgetTier = 1 | 2 | 3 | 4;

export type PlaceSource = "osm_seed" | "manual" | "discovery";
export type PlaceStatus = "active" | "needs_review" | "blocked";
export type EventStatus = "open" | "closed" | "cancelled";
export type RsvpResponse = "yes" | "no" | "maybe";

// ---------------------------------------------------------------------------
// Core entities
// ---------------------------------------------------------------------------

export interface Office {
  id: string;
  name: string;
  address?: string | null;
  lat: number;
  lng: number;
  created_at?: string;
}

export interface Place {
  id: string;
  name: string;
  address?: string | null;
  lat: number;
  lng: number;
  cuisine: string[];
  /**
   * Free-text tags typed through the "Other" chip. Display-only — shown
   * alongside `cuisine` on the card, but never read by recommendConfig.ts /
   * recommend.ts, so a junk tag can't quietly nudge rankings.
   */
  custom_cuisine_tags: string[];
  budget_tier: BudgetTier;
  osm_id?: number | null;
  source: PlaceSource;
  status: PlaceStatus;
  best_dishes: string[];
  notes?: string | null;
  created_by?: string | null;
  created_at?: string;
  updated_at?: string;

  /** Derived, not stored: minutes on foot from the active office. */
  walk_minutes?: number | null;
  /** Derived, not stored: metres from the active office. */
  distance_m?: number | null;
  /** Derived, not stored: mean of all ratings across visits. */
  avg_rating?: number | null;
  /** Derived, not stored: how many visits have been logged. */
  visit_count?: number;
  /** Trigger-maintained: true while at least one flag on this place is
   *  unresolved (022_place_flags.sql). Shows a "Reported" badge — the place
   *  stays fully active until an admin resolves it. */
  has_pending_flag?: boolean;
  /**
   * Derived, not stored, and only populated when `/places` is sorted by
   * "rated by your Kaki group" (§12f) — the mean rating among visits logged
   * by anyone in one of the requesting user's Kaki groups, themself
   * included. `null`/absent means nobody in the group has rated it, not a
   * rating of zero.
   */
  kaki_rating?: number | null;
}

export interface Visit {
  id: string;
  place_id: string;
  user_id: string;
  rating: number;
  best_dishes: string[];
  notes?: string | null;
  visited_at: string;
  created_at?: string;
  is_public: boolean;

  /** Derived, only populated on review listings. */
  display_name?: string;
  /** Derived, only populated on review listings. */
  place_name?: string;
}

export interface WalkCacheEntry {
  office_id: string;
  place_id: string;
  walk_minutes: number;
  distance_m: number;
  computed_at?: string;
}

export interface UserPrefs {
  user_id: string;
  cuisine_likes: string[];
  cuisine_dislikes: string[];
  budget_min: BudgetTier;
  budget_max: BudgetTier;
  blocklist: string[];
  default_office_id?: string | null;
}

export interface Profile {
  user_id: string;
  display_name: string;
  created_at?: string;
  /** Null until the one-time /welcome screen has been completed. */
  onboarded_at?: string | null;
}

export interface TeamUser {
  user_id: string;
  display_name: string;
}

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------

/** Null/undefined means "not a Flexi Jio" — every regular fixed-date event. */
export type DatePhase = "polling" | "confirmed";

export interface LunchEvent {
  id: string;
  office_id: string;
  host_id: string;
  title: string;
  /** For a polling Flexi Jio, a provisional value (the earliest candidate
   *  date) rather than a real commitment — check `date_phase` first. */
  scheduled_at: string;
  status: EventStatus;
  invite_token: string;
  winner_place_id?: string | null;
  kaki_id?: string | null;
  date_phase?: DatePhase | null;
  /** Set when this occurrence was generated by a recurring series. */
  recurring_series_id?: string | null;
  /**
   * Set only at creation, never editable after — a host-write-only setting,
   * not a `status`-class field. While `true` and `status === "open"`, every
   * API route redacts `votes`/`tally` from its response (see
   * `redactHiddenVotes` in `lib/voting.ts`); once closed, hidden votes reveal
   * like any other Jio.
   */
  hide_votes?: boolean;
  /** Set once, when `closeEvent` runs — powers §13b's time-to-decision
   *  metric. `null`/absent for anything still open or cancelled. */
  closed_at?: string | null;
  created_at?: string;

  /** Derived. */
  host_name?: string;
  /** Derived. */
  option_count?: number;
  /** Derived. */
  going_count?: number;
  /** Derived. */
  winner_place_name?: string | null;
  /**
   * Derived. Set only when the winner is a free-text option with no place
   * record behind it — the label to show in place of `winner_place_name`.
   */
  winner_label?: string | null;
  /** Derived. Only meaningful for a polling Flexi Jio — has the requesting
   *  user already marked any availability on it? Powers the home page's
   *  "Needs your availability" list without a full per-event fetch. */
  has_marked_availability?: boolean;
}

export type RecurringSeriesMode = "vote" | "fixed";
export type RecurringSeriesStatus = "active" | "cancelled";

/**
 * A standing weekly Jio — CHANGES_20260801.md §10 ("Recurring Jios —
 * extended"). This is a generator, not an event: `generateDueOccurrences`
 * turns it into an ordinary `LunchEvent` each week, which is where all the
 * normal voting/RSVP/close machinery actually lives.
 */
export interface RecurringSeries {
  id: string;
  host_id: string;
  title: string;
  office_id?: string | null;
  kaki_id?: string | null;
  invitee_ids: string[];
  /** 0 = Sunday .. 6 = Saturday. */
  weekday: number;
  /** "HH:MM", 24-hour. */
  time_of_day: string;
  mode: RecurringSeriesMode;
  /** Set only when `mode` is "fixed". */
  fixed_place_id?: string | null;
  /** Set only when `mode` is "vote" — seeded into every occurrence. */
  option_place_ids: string[];
  status: RecurringSeriesStatus;
  /** ISO date ("YYYY-MM-DD") of the most recently generated occurrence. */
  last_generated_date?: string | null;
  created_at?: string;

  /** Derived. */
  fixed_place_name?: string | null;
}

export interface EventCandidateDate {
  event_id: string;
  /** ISO date, "YYYY-MM-DD" — day-level, no time component. */
  date: string;
  added_by: string;
  created_at?: string;

  /** Derived. */
  added_by_name?: string;
}

/** One user marking themselves free on one candidate date. */
export interface EventDateVote {
  event_id: string;
  user_id: string;
  date: string;
  created_at?: string;

  /** Derived. */
  display_name?: string;
}

export interface EventOption {
  event_id: string;
  /**
   * Always set — never truly null. For a free-text option (see `label`)
   * this is a generated id with no matching row in `places`, not a
   * placeholder; it's what makes the option votable through the exact same
   * `event_votes.place_id` column real places use, with no schema fork.
   */
  place_id: string;
  added_by: string;
  /** True for a "Can't decide? Suggest 3" pick, false for a manual add. */
  is_suggested: boolean;
  /**
   * Set only for a free-text option added when a search had no results —
   * "vote first, prompt after" (see CHANGES_20260801.md §8). `place` will be
   * undefined whenever this is set. Cleared if the option is later attached
   * to a real place via `attachPlaceToOption`.
   */
  label?: string | null;

  /** Derived. */
  place?: Place;
  /** Derived. */
  added_by_name?: string;
}

export interface EventVote {
  event_id: string;
  user_id: string;
  place_id: string;
  rank: number;
  created_at?: string;
}

export interface EventRsvp {
  event_id: string;
  user_id: string;
  response: RsvpResponse;

  /** Derived. */
  display_name?: string;
}

export interface EventInvitee {
  event_id: string;
  user_id: string;

  /** Derived. */
  display_name?: string;
}

export interface EventDetail extends LunchEvent {
  options: EventOption[];
  votes: EventVote[];
  rsvps: EventRsvp[];
  invitees: EventInvitee[];
  /** Live Borda tally, keyed by place id. Redacted to `{}` while hidden. */
  tally?: Record<string, number>;
  /**
   * Count of distinct voters — always populated by every route, so the
   * client never has to fall back to counting `votes` itself, which is
   * empty while a hidden-vote Jio's standing is redacted.
   */
  voter_count?: number;
  /** Only meaningful for a Flexi Jio (`date_phase` set). */
  candidateDates: EventCandidateDate[];
  /** Only meaningful for a Flexi Jio (`date_phase` set). */
  dateVotes: EventDateVote[];
}

// ---------------------------------------------------------------------------
// Wishlist, recos, kakis
// ---------------------------------------------------------------------------

export interface WishlistEntry {
  user_id: string;
  place_id: string;
  created_at?: string;

  /** Derived. */
  place?: Place;
}

/**
 * A "lobang" — Singlish for a tip-off — is a personalized place
 * recommendation one teammate sends directly to another (or to every member
 * of a Kaki at once — see `kaki_id`), never a broadcast to the whole team.
 *
 * Recipients live in a separate `lobang_recipients` table (snapshotted at
 * send time), so this object's shape depends on which `Repo` method produced
 * it: `listLobangsReceived` hydrates it for one specific recipient's view
 * (`to_user_id`/`seen_at` are that viewer's own); `listLobangsSent` hydrates
 * it as the send itself (`to_display_name` summarizes every recipient, or
 * names the Kaki for a group send).
 */
export interface Lobang {
  id: string;
  from_user_id: string;
  place_id: string;
  note?: string | null;
  /** The past Jio this was sent from, if any. Purely informational. */
  event_id?: string | null;
  /** Set only for a group send. Display provenance only — the actual
   *  recipient list always lives in `lobang_recipients`. */
  kaki_id?: string | null;
  created_at?: string;

  /** Derived. Populated only on a `listLobangsReceived` row, or a
   *  single-recipient `listLobangsSent` row. */
  to_user_id?: string;
  /** Derived. Null until that recipient has seen it. */
  seen_at?: string | null;

  /** Derived. */
  from_display_name?: string;
  /** Derived. Who/what this went to, as one string — a teammate's name for
   *  an individual send, or the Kaki's name for a group send. */
  to_display_name?: string;
  /** Derived. */
  place?: Place;
  /** Derived. */
  event_title?: string | null;
}

/** Who a lobang is being sent to — specific teammates, or a whole Kaki. */
export type LobangTarget =
  | { type: "users"; userIds: string[] }
  | { type: "kaki"; kakiId: string };

/**
 * One block or unblock event. "Removing" a place always means flipping its
 * status, never deleting the row — this log is the trail of who did that,
 * when, and (for a block) why.
 */
export interface ModerationLogEntry {
  id: string;
  place_id: string;
  actor_id: string;
  action: "block" | "unblock";
  reason?: string | null;
  created_at?: string;

  /** Derived. */
  place_name?: string;
  actor_display_name?: string;
}

// ---------------------------------------------------------------------------
// Place flags
// ---------------------------------------------------------------------------

export type FlagReason =
  | "closed"
  | "wrong_info"
  | "duplicate"
  | "inappropriate"
  | "other";

/** "blocked" means an admin resolved the flag(s) by blocking the place —
 *  reuses the same status/log an ordinary block_place() call would. */
export type FlagResolution = "dismissed" | "edited" | "blocked";

export interface PlaceFlag {
  id: string;
  place_id: string;
  flagged_by: string;
  reason: FlagReason;
  comment?: string | null;
  status: "pending" | "resolved";
  resolution?: FlagResolution | null;
  resolved_by?: string | null;
  resolved_at?: string | null;
  created_at?: string;

  /** Derived. */
  place_name?: string;
  /** Derived. */
  flagged_by_name?: string;
}

export interface Kaki {
  id: string;
  name: string;
  created_by: string;
  invite_token: string;
  created_at?: string;

  /** Derived. */
  member_count?: number;
}

export interface KakiMember {
  kaki_id: string;
  user_id: string;
  joined_at?: string;

  /** Derived. */
  display_name?: string;
}

export interface KakiDetail extends Kaki {
  members: KakiMember[];
}

// ---------------------------------------------------------------------------
// Recommendation engine
// ---------------------------------------------------------------------------

export interface ScoreBreakdown {
  cuisineAffinity: number;
  bayesianRating: number;
  budgetFit: number;
  walkPenalty: number;
  varietyBonus: number;
  wishlistBoost: number;
}

export interface ScoredPlace {
  place: Place;
  score: number;
  breakdown: ScoreBreakdown;
  /** The single component that contributed most to the score. */
  topReason: keyof ScoreBreakdown;
}

export interface RankOptions {
  /** Multiplier applied to the walk penalty. 2 when rain is likely. */
  weatherMultiplier?: number;
  /** Injected clock, for deterministic tests. */
  now?: Date;
  /** Cap on how many results to return. */
  limit?: number;
  /** Restrict to these cuisines. */
  cuisines?: string[];
  /** Cap on walking minutes. */
  maxWalkMinutes?: number;
}

export interface MemberData {
  userId: string;
  visits: Visit[];
  prefs: UserPrefs | null;
  wishlistPlaceIds: string[];
}

// ---------------------------------------------------------------------------
// Filters
// ---------------------------------------------------------------------------

export interface Filters {
  cuisines: string[];
  budgetMin: BudgetTier;
  budgetMax: BudgetTier;
  maxWalkMinutes: number;
  status: PlaceStatus | "all";
  search: string;
  officeId: string;
  /**
   * Defaults to "walk" (nearest first) when omitted. "kaki_rating" is
   * handled entirely at the API route layer (see §12f in
   * src/app/api/places/route.ts) — the repo has no concept of "the
   * requesting user's Kaki groups," so it's never passed down here.
   */
  sortBy?: "walk" | "rating";
}

export interface PlacesPagination {
  limit: number;
  offset: number;
}

export interface PlacesPage {
  places: Place[];
  /** Total matching rows, ignoring `limit`/`offset` — for a "Load more" count. */
  total: number;
}

// ---------------------------------------------------------------------------
// Metrics
// ---------------------------------------------------------------------------

export interface FavouritePlace {
  place_id: string;
  place_name: string;
  visit_count: number;
  avg_rating: number;
}

export interface UserMetrics {
  totalVisits: number;
  distinctPlaces: number;
  favouritePlaces: FavouritePlace[];
  avgRatingGiven: number;
  cuisineBreakdown: Record<string, number>;
  avgBudgetTier: number;
  avgBudgetLabel: string;
  mostActiveMonth: string | null;
  currentVariety: number;
}

export interface KakiMetrics {
  groupTotalVisits: number;
  groupDistinctPlaces: number;
  groupFavouritePlaces: FavouritePlace[];
  groupAvgBudgetTier: number;
  groupAvgBudgetLabel: string;
  groupCuisineBreakdown: Record<string, number>;
  mostActiveMember: { user_id: string; visits: number } | null;
  adventurer: { user_id: string; distinctPlaces: number } | null;
}

export interface CuisineStreak {
  cuisine: string;
  days: number;
}

/** One point in a day- or week-bucketed count series, Asia/Singapore day
 *  boundary per CHANGES_20260803_1.md §13c. `date` is the bucket start,
 *  ISO "YYYY-MM-DD". */
export interface DateCount {
  date: string;
  count: number;
}

export interface NamedCount {
  id: string;
  name: string;
  count: number;
}

/**
 * §13 admin analytics dashboard, Phase 1 (in-app). Covers a fixed 90-day
 * trailing window, no date-range picker in v1 (§13c). Two fields the spec
 * asked for aren't here because the schema doesn't carry the timestamp
 * they'd need yet — see the doc comments on those two entries below rather
 * than treating the gap as an oversight.
 */
export interface AdminAnalytics {
  windowDays: number;
  generatedAt: string;

  funnel: {
    /** Today only (Asia/Singapore), not a window total — a funnel is a
     *  snapshot of "who did what today," not a 90-day sum. */
    participatingDau: number;
    /**
     * Lifetime total, not a daily figure — `event_rsvps` has no timestamp
     * column, so "responded today" isn't something the current schema can
     * answer. Worth adding `responded_at` if this funnel stays a priority.
     */
    respondedToInviteTotal: number;
    votedInJioToday: number;
    hostedJioToday: number;
  };

  growth: {
    newUsersPerDay: DateCount[];
    jiosCreatedPerDay: DateCount[];
    /**
     * All places created, any path. The Growth table asked for a split
     * between "added via a Jio" and "added via /places/new" — both paths
     * insert through the same `places` row with no field distinguishing
     * how it got there, so that split isn't derivable from the current
     * schema without adding one.
     */
    placesAddedPerDay: DateCount[];
    kakiGroupsCreatedPerDay: DateCount[];
    kakiGroupsCumulative: number;
  };

  jioOutcomes: {
    decided: number;
    closedNoWinner: number;
    cancelled: number;
    stillOpen: number;
    avgBallotsPerJio: number;
    /** `null` when no Jio in the window has both `created_at` and
     *  `closed_at` to measure between. */
    medianTimeToDecisionHours: number | null;
  };

  content: {
    /** Floored to places with at least 3 visits, so one glowing review
     *  can't sit at the top of the list. */
    topRatedPlaces: (NamedCount & { avgRating: number })[];
    mostVisitedPlaces: NamedCount[];
    /** Named-category counts only — a custom "Other" tag is free text, not
     *  a category to break out individually. */
    cuisineDistribution: Record<string, number>;
    customCuisineTagUsageCount: number;
    walkTimeBuckets: { bucket: string; count: number }[];
  };

  social: {
    mostActiveKakis: NamedCount[];
    groupSizeDistribution: { size: number; count: number }[];
  };

  moderation: {
    reportsFiledPerWeek: DateCount[];
    reportsResolvedPerWeek: DateCount[];
    avgResolutionHours: number | null;
    pendingCount: number;
  };

  wishlist: {
    savesPerWeek: DateCount[];
    mostSavedPlaces: NamedCount[];
  };
}

// ---------------------------------------------------------------------------
// External services
// ---------------------------------------------------------------------------

export interface WalkingRoute {
  distance_m: number;
  walk_minutes: number;
  /** Decoded [lat, lng] pairs, when the provider returns geometry. */
  polyline?: [number, number][];
  /** Which provider produced this result. */
  source: "onemap" | "haversine";
}

export interface WeatherForecast {
  area: string;
  forecast: string;
  validity: string;
  rainLikely: boolean;
}

export interface OverpassElement {
  type: "node" | "way" | "relation";
  id: number;
  lat?: number;
  lon?: number;
  center?: { lat: number; lon: number };
  tags?: Record<string, string>;
}

export interface PlaceCandidate {
  name: string;
  lat: number;
  lng: number;
  cuisine: string[];
  budget_tier: BudgetTier;
  osm_id: number;
  source: PlaceSource;
  status: PlaceStatus;
  address?: string | null;
}

// ---------------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------------

export interface AuthUser {
  id: string;
  email: string | null;
  display_name?: string | null;
}
